# Generated by Django 3.2 on 2021-04-24 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ags', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=255)),
                ('division_category', models.IntegerField()),
                ('division_type', models.CharField(choices=[(10, 'Bundesland'), (20, 'Regierungsbezirk'), (30, 'Region'), (40, 'Kreis'), (41, 'Kreisfreie Stadt'), (42, 'Stadtkreis'), (43, 'Kreis'), (44, 'Landkreis'), (45, 'Regionalverband'), (50, 'verbandsfreie Gemeinde'), (51, 'Amt'), (52, 'Samtgemeinde'), (53, 'Verbandsgemeinde'), (54, 'Verwaltungsgemeinschaft'), (55, 'Kirchspielslandgemeinde'), (56, 'Verwaltungsverband'), (57, 'VG Trägermodell'), (58, 'Erfüllende Gemeinde'), (60, 'Markt'), (61, 'Kreisfreie Stadt'), (62, 'Stadtkreis'), (63, 'Stadt'), (64, 'Kreisangehörige Gemeinde'), (65, 'gemeindefreies Gebiet, bewohnt'), (66, 'gemeindefreies Gebiet, unbewohnt'), (67, 'große Kreisstadt')], max_length=64)),
                ('office_zip', models.IntegerField(blank=True)),
                ('office_street', models.CharField(blank=True, max_length=255)),
                ('office_city', models.CharField(blank=True, max_length=255)),
                ('area', models.FloatField(blank=True)),
                ('citizens_total', models.IntegerField(blank=True)),
                ('citizens_female', models.IntegerField(blank=True)),
                ('citizens_male', models.IntegerField(blank=True)),
                ('population_density', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('latitude', models.FloatField(blank=True)),
                ('TRAVEL_CODE', models.CharField(blank=True, max_length=4)),
                ('TRAVLE_NAME', models.CharField(blank=True, max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gvz.administrativedivision')),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('administrative_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gvz.administrativedivision')),
            ],
        ),
    ]
