# Generated by Django 3.2 on 2021-04-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrativedivision',
            old_name='TRAVEL_CODE',
            new_name='travel_code',
        ),
        migrations.RenameField(
            model_name='administrativedivision',
            old_name='TRAVLE_NAME',
            new_name='travel_name',
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='ags',
            field=models.IntegerField(unique=True),
        ),
    ]
