# Generated by Django 3.2 on 2021-04-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvz', '0004_alter_administrativedivision_division_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='division_category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
