# Generated by Django 3.2 on 2021-04-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvz', '0005_alter_administrativedivision_division_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='citizens_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='citizens_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='citizens_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='office_city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='office_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='office_zip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='population_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='travel_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='travel_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
