# Generated by Django 3.2 on 2021-04-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvz', '0006_auto_20210424_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='office_zip',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
