# Generated by Django 3.2 on 2021-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvz', '0007_auto_20210424_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='zipcode',
            unique_together={('zip_code', 'administrative_division')},
        ),
    ]
