# Generated by Django 3.2 on 2021-04-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvz', '0008_auto_20210424_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='division_category',
            field=models.IntegerField(blank=True, choices=[(10, 'Bundesland'), (20, 'Regierungsbezirk'), (30, 'Region'), (40, 'Kreis'), (50, 'Gemeindeverband'), (60, 'Gemeinde')], null=True),
        ),
        migrations.AlterField(
            model_name='administrativedivision',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gvz.administrativedivision'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='administrative_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='gvz.administrativedivision'),
        ),
    ]
