# Generated by Django 3.2 on 2021-04-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gvz', '0009_auto_20210425_0937'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='administrativedivision',
            index=models.Index(fields=['ags'], name='gvz_adminis_ags_59daa5_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativedivision',
            index=models.Index(fields=['division_type'], name='gvz_adminis_divisio_a636f7_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativedivision',
            index=models.Index(fields=['division_category'], name='gvz_adminis_divisio_0cb071_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativedivision',
            index=models.Index(fields=['name'], name='gvz_adminis_name_9b5202_idx'),
        ),
        migrations.AddIndex(
            model_name='zipcode',
            index=models.Index(fields=['zip_code'], name='gvz_zipcode_zip_cod_325ace_idx'),
        ),
    ]
