# Generated by Django 3.2 on 2021-04-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gvz', '0010_auto_20210425_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedivision',
            name='division_type',
            field=models.IntegerField(blank=True, choices=[(10, 'Bundesland'), (20, 'Regierungsbezirk'), (30, 'Region'), (40, 'Kreis'), (41, 'Kreisfreie Stadt'), (42, 'Stadtkreis'), (43, 'Kreis'), (44, 'Landkreis'), (45, 'Regionalverband'), (50, 'verbandsfreie Gemeinde'), (51, 'Amt'), (52, 'Samtgemeinde'), (53, 'Verbandsgemeinde'), (54, 'Verwaltungsgemeinschaft'), (55, 'Kirchspielslandgemeinde'), (56, 'Verwaltungsverband'), (57, 'VG Trägermodell'), (58, 'Erfüllende Gemeinde'), (60, 'Markt'), (61, 'Kreisfreie Stadt'), (62, 'Stadtkreis'), (63, 'Stadt'), (64, 'Kreisangehörige Gemeinde'), (65, 'gemeindefreies Gebiet, bewohnt'), (66, 'gemeindefreies Gebiet, unbewohnt'), (67, 'große Kreisstadt')], null=True),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='administrative_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes_objects', to='gvz.administrativedivision'),
        ),
    ]
